# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 18:04
from __future__ import unicode_literals

import apiweb.apps.main.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretary_email_address', models.EmailField(default='secr-astro-science@uva.nl', max_length=254, verbose_name='API Secretariat e-mail address')),
                ('address_api', models.CharField(default='Sciencepark 904, 1098XH, Amsterdam', max_length=256, verbose_name='API Address')),
                ('postbox_address_api', models.CharField(default='PO Box 94249, 1090 GE Amsterdam', max_length=256, verbose_name='API PO Box Address')),
                ('telephone_api', models.CharField(default='0031205257491', max_length=20, verbose_name='API Phone Number')),
                ('webmaster_email_address', models.EmailField(default='secr-astro-science@uva.nl', max_length=254, verbose_name='API Webmaster e-mail address')),
            ],
            options={
                'verbose_name': 'API Contact Info',
                'verbose_name_plural': 'API Contact Info',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', tinymce.models.HTMLField(blank=True, verbose_name='Privacy Policy')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, default='Lorum Ipsum', verbose_name='Welcome Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apiweb.apps.main.models.place_welcome_photo, verbose_name='Welcome Photo')),
            ],
            options={
                'verbose_name': 'Welcome Page',
                'verbose_name_plural': 'Welcome Page',
            },
        ),
    ]
