# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:16
from __future__ import unicode_literals

import api.apps.people.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_person', models.BooleanField(default=True, verbose_name='person visible on website')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='first name')),
                ('prefix', models.CharField(blank=True, max_length=40, verbose_name='prefix')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Unknown')], null=True, verbose_name='gender')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='title')),
                ('initials', models.CharField(blank=True, max_length=40, verbose_name='initials')),
                ('ads_name', models.CharField(blank=True, max_length=40, verbose_name='ads name')),
                ('address', models.CharField(blank=True, max_length=40, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=40, verbose_name='zipcode')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=40, verbose_name='country')),
                ('home_phone', models.CharField(blank=True, max_length=40, verbose_name='home telephone')),
                ('work_phone', models.CharField(blank=True, max_length=40, verbose_name='work telephone')),
                ('mobile', models.CharField(blank=True, max_length=40, verbose_name='mobile')),
                ('office', models.CharField(blank=True, max_length=40, verbose_name='office')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Director'), (2, 'Faculty Staff'), (3, 'Nova'), (4, 'Adjunct Staff'), (5, 'Postdoc'), (6, 'PhD Student'), (7, 'Emeritus'), (8, 'Guest'), (9, 'Master Student'), (10, 'Bachelor Student'), (11, 'Software Developer')], default=5, verbose_name='position')),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to=api.apps.people.models.get_mugshot_location, verbose_name='mugshot')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.apps.people.models.get_photo_location, verbose_name='photo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='homepage')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('contact', models.ManyToManyField(blank=True, related_name='contact', to='research.ResearchTopic', verbose_name='contact')),
                ('research', models.ManyToManyField(blank=True, related_name='interest', to='research.ResearchTopic', verbose_name='research')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
