# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(blank=True, max_length=40, verbose_name='position name')),
                ('current_job', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2, verbose_name='current occupation')),
                ('company_name', models.CharField(blank=True, max_length=40, verbose_name='company name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date start job')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='date start job')),
                ('inside_academia', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1, verbose_name='inside academia')),
                ('location_job', models.PositiveSmallIntegerField(choices=[(1, 'NL'), (2, 'Europe'), (3, 'Great Bitain'), (4, 'US'), (5, 'Other')], default=1, verbose_name='location job')),
            ],
        ),
        migrations.CreateModel(
            name='MastersDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_master', models.DateField(blank=True, null=True, verbose_name='date start master')),
                ('date_stop_master', models.DateField(blank=True, null=True, verbose_name='date stop master')),
            ],
        ),
        migrations.CreateModel(
            name='PhdDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_phd', models.DateField(blank=True, null=True, verbose_name='date start phd')),
                ('date_stop_phd', models.DateField(blank=True, null=True, verbose_name='date stop phd')),
                ('phd_defence_date', models.DateField(blank=True, null=True, verbose_name='phd defence date')),
            ],
        ),
        migrations.CreateModel(
            name='PostdocPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_postdoc', models.DateField(blank=True, null=True, verbose_name='date start postdoc')),
                ('date_stop_postdoc', models.DateField(blank=True, null=True, verbose_name='date stop postdoc')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, max_length=40, verbose_name='nationality'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=40, verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='person',
            name='streetname',
            field=models.CharField(blank=True, max_length=40, verbose_name='streetname'),
        ),
        migrations.AddField(
            model_name='person',
            name='streetnumber',
            field=models.CharField(blank=True, max_length=40, verbose_name='streetnumber'),
        ),
        migrations.AddField(
            model_name='person',
            name='jobs',
            field=models.ManyToManyField(to='people.Job'),
        ),
    ]
