# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 18:04
from __future__ import unicode_literals

import apiweb.apps.research.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phd', 'PhD'), ('msc', 'Master of Science'), ('bsc', 'Bachelor of Science')], default='PhD', max_length=3)),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Starting date')),
                ('date_stop', models.DateField(blank=True, null=True, verbose_name='Date finished')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Thesis Title')),
                ('date_of_defence', models.DateField(blank=True, help_text='Date of the thesis or defense', null=True, verbose_name='Defence date')),
                ('url', models.URLField(blank=True, help_text='UvA DARE or other URL to thesis', null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('dissertation_nr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PhD Dissertation Counter')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=apiweb.apps.research.models.get_thesis_pdf_location, verbose_name='Full Text (pdf)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apiweb.apps.research.models.get_thesis_photo_location, verbose_name='Thesis Photo')),
                ('in_library', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Last Changed')),
                ('advisor', models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MSc and/or PhD Thesis at API',
                'verbose_name_plural': 'MSc and/or PhD Theses at API',
            },
        ),
    ]
