# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Use format: YYYY-MM-DD', verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_of_defence',
            field=models.DateField(blank=True, help_text='Date of the thesis or defense. Use format: YYYY-MM-DD', null=True, verbose_name='Defence date'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_start',
            field=models.DateField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='Starting date'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_stop',
            field=models.DateField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='Date finished'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Use format: YYYY-MM-DD', verbose_name='Date Last Changed'),
        ),
    ]
