# Generated by Django 2.2.3 on 2019-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180103_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='in_library',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
