# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40, unique=True, verbose_name='research topic')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Neutron stars and black holes'), (2, 'Cosmic explosions'), (3, 'Astroparticle physics'), (4, 'Planet formation and exoplanets'), (5, 'Stars, formation and evolution')], verbose_name='category')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/images/research/topics/', verbose_name='picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'research topic',
                'verbose_name_plural': 'research topics',
                'ordering': ('topic',),
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Unknown')], null=True, verbose_name='gender')),
                ('title', models.CharField(default='Title Unknown', max_length=160)),
                ('date', models.DateField(help_text='Date of the thesis or defense')),
                ('type', models.CharField(choices=[('phd', 'PhD'), ('msc', 'Master'), ('bsc', 'Bachelor')], default='PhD', max_length=3)),
                ('url', models.URLField(blank=True, help_text='UvA DARE URL or other URL to thesis')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'thesis',
                'verbose_name_plural': 'theses',
            },
        ),
    ]
