# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:49
from __future__ import unicode_literals

import apiweb.apps.alumni.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, unique=True, validators=[apiweb.apps.alumni.validators.MyValidator()], verbose_name='username'),
        ),
    ]
