# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20180103_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='survey_email_sent',
            field=models.DateTimeField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='Date survey email sent'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Use format: YYYY-MM-DD', verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Use format: YYYY-MM-DD', verbose_name='Date Last Changed'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='Update this field if you know that the contact information is up-to-date. Use format: YYYY-MM-DD', null=True, verbose_name='Date Last Checked'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='survey_info_updated',
            field=models.DateTimeField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='Date survey info updated'),
        ),
        migrations.AlterField(
            model_name='previousposition',
            name='date_start',
            field=models.DateField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='Starting date'),
        ),
        migrations.AlterField(
            model_name='previousposition',
            name='date_stop',
            field=models.DateField(blank=True, help_text='Use format: YYYY-MM-DD', null=True, verbose_name='Date finished'),
        ),
    ]
