# Generated by Django 2.2.3 on 2019-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20180103_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='passed_away',
            field=models.BooleanField(blank=True, default=False, help_text='If selected an asterisk will appear by the name of this alumnus on the website.', verbose_name='Deceased'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='show_biography',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show biography on personal page'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='show_email',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show email on personal page'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='show_facebook',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show facebook on personal page'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='show_homepage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show homepage on personal page'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='show_linkedin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show linkedin on personal page'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='show_twitter',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show twitter on personal page'),
        ),
    ]
