# Generated by Django 2.2.6 on 2019-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20190711_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
    ]
