# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobafterleaving',
            name='is_inside_astronomy',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True, verbose_name='In Astronomy'),
        ),
    ]
