# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=40, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=40, verbose_name='zipcode')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=40, verbose_name='country')),
                ('home_phone', models.CharField(blank=True, max_length=40, verbose_name='home telephone')),
                ('work_phone', models.CharField(blank=True, max_length=40, verbose_name='work telephone')),
                ('mobile', models.CharField(blank=True, max_length=40, verbose_name='mobile')),
                ('office', models.CharField(blank=True, max_length=40, verbose_name='office')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_person', models.BooleanField(default=True, verbose_name='person visible on website')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='first name')),
                ('prefix', models.CharField(blank=True, max_length=40, verbose_name='prefix')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Unknown')], null=True, verbose_name='gender')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='title')),
                ('initials', models.CharField(blank=True, max_length=40, verbose_name='initials')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='alumni.Person'),
        ),
    ]
