name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    services:
      mariadb:
        image: mariadb:10.3
        ports:
          - 3306
        env:
          MYSQL_DATABASE: apiweb
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: no
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements_production.txt') }}-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_production.txt ]; then pip install -r requirements_production.txt; fi

      - name: Setup .env
        run: |
          cp apiweb/settings/.env.example apiweb/settings/.env
          sed -i.bak -e "s/DATABASE_DEFAULT=.*/DATABASE_DEFAULT=mysql:\/\/root:root@127.0.0.1:${{ job.services.mariadb.ports[3306] }}\/apiweb/g" apiweb/settings/.env
          grep "DATABASE_DEFAULT" apiweb/settings/.env

      - name: Run the tests
        run: python manage.py test
